apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world-application
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/git-branch: main
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/github-creds
    argocd-image-updater.argoproj.io/image-list: message-server=docker.io/ndthanht36/message-server
    argocd-image-updater.argoproj.io/message-server.update-strategy: latest
    argocd-image-updater.argoproj.io/message-server.force-update: "true"
spec:
  project: default

  source:
    repoURL: https://github.com/thanhnd1709/hello-world
    targetRevision: HEAD
    path: hello-world
    helm:
      valueFiles:
      - values.yaml 
  destination: 
    server: https://kubernetes.default.svc
    namespace: hello-world

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
